name = "ISO13373"
uuid = "edbbe35f-bdfd-4174-8e13-421f0fdec38e"
version = "0.1.0"
authors = ["Serin Thomas <75860641+sentomas@users.noreply.github.com>"]

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
Genie = "5.33.16"
JSON3 = "1.14.3"
