[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
